/**
 * タスクデモデータ
 * @see docs/DEMO_SHOWCASE_SPEC.md セクション4
 *
 * 期限アラート・提供リマインダーなどのタスクデータ
 */

import type { Task, TaskStatus, TaskType, TaskPriority } from '../../types/task';

// ===== 日付ヘルパー =====

function getDateString(daysFromToday: number): string {
  const date = new Date();
  date.setDate(date.getDate() + daysFromToday);
  return date.toISOString().split('T')[0];
}

function getDateTimeString(daysFromToday: number, hour = 9, minute = 0): string {
  const date = new Date();
  date.setDate(date.getDate() + daysFromToday);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

// ===== デモタスクデータ =====

export const DEMO_TASKS: Task[] = [
  // ===== 期限警告タスク =====
  {
    id: 'task-001',
    residentId: 'resident-001',
    title: '柿（熟し）の賞味期限が明日です',
    description: '2個中2個が未提供です。早めの提供をお願いします。ご本人の好物なので、熟した部分も捨てずに提供してください。',
    taskType: 'expiration_warning' as TaskType,
    relatedItemId: 'demo-item-005',
    dueDate: getDateString(0),
    dueTime: '12:00',
    status: 'pending' as TaskStatus,
    priority: 'urgent' as TaskPriority,
    notificationSent: true,
    isAutoGenerated: true,
    createdBy: 'system',
    createdAt: getDateTimeString(-1, 8),
    updatedAt: getDateTimeString(-1, 8),
  },
  {
    id: 'task-002',
    residentId: 'resident-001',
    title: 'プリンの賞味期限が明日です',
    description: '残り2個。大好物なので本日中の提供を推奨します。',
    taskType: 'expiration_warning' as TaskType,
    relatedItemId: 'demo-item-006',
    dueDate: getDateString(0),
    dueTime: '15:00',
    status: 'pending' as TaskStatus,
    priority: 'high' as TaskPriority,
    notificationSent: true,
    isAutoGenerated: true,
    createdBy: 'system',
    createdAt: getDateTimeString(-1, 8),
    updatedAt: getDateTimeString(-1, 8),
  },
  {
    id: 'task-003',
    residentId: 'resident-001',
    title: 'バナナの賞味期限が近づいています',
    description: '2日後に期限切れ。残り1.5房。毎日0.5房ずつ提供中。',
    taskType: 'expiration_warning' as TaskType,
    relatedItemId: 'demo-item-001',
    dueDate: getDateString(1),
    dueTime: '12:00',
    status: 'pending' as TaskStatus,
    priority: 'medium' as TaskPriority,
    notificationSent: false,
    isAutoGenerated: true,
    createdBy: 'system',
    createdAt: getDateTimeString(0, 8),
    updatedAt: getDateTimeString(0, 8),
  },

  // ===== 提供リマインダー =====
  {
    id: 'task-004',
    residentId: 'resident-001',
    title: 'バナナの昼食提供',
    description: '0.5房を提供予定。皮を剥いてカットして提供。',
    taskType: 'serve_reminder' as TaskType,
    relatedItemId: 'demo-item-001',
    dueDate: getDateString(0),
    dueTime: '12:00',
    status: 'in_progress' as TaskStatus,
    priority: 'medium' as TaskPriority,
    assignee: '田中花子',
    notificationSent: true,
    isAutoGenerated: true,
    createdBy: 'system',
    createdAt: getDateTimeString(0, 6),
    updatedAt: getDateTimeString(0, 11),
  },
  {
    id: 'task-005',
    residentId: 'resident-001',
    title: 'おやつ時間：プリン提供',
    description: '15:00のおやつ時間に提供予定。冷蔵庫から出してすぐ提供。',
    taskType: 'serve_reminder' as TaskType,
    relatedItemId: 'demo-item-006',
    dueDate: getDateString(0),
    dueTime: '15:00',
    status: 'pending' as TaskStatus,
    priority: 'medium' as TaskPriority,
    notificationSent: false,
    isAutoGenerated: true,
    createdBy: 'system',
    createdAt: getDateTimeString(0, 6),
    updatedAt: getDateTimeString(0, 6),
  },

  // ===== ケア指示タスク =====
  {
    id: 'task-006',
    residentId: 'resident-001',
    title: 'りんごの提供方法確認',
    description: '摂食率が25%と低い状態です。提供方法の変更を検討してください。すりおろし or ジュースにするなど。',
    taskType: 'care_instruction' as TaskType,
    relatedItemId: 'demo-item-003',
    dueDate: getDateString(1),
    status: 'pending' as TaskStatus,
    priority: 'medium' as TaskPriority,
    notificationSent: false,
    isAutoGenerated: false,
    createdBy: 'family-001',
    createdAt: getDateTimeString(-1, 10),
    updatedAt: getDateTimeString(-1, 10),
  },

  // ===== 完了済みタスク =====
  {
    id: 'task-007',
    residentId: 'resident-001',
    title: 'キウイの提供（8等分・半月切り）',
    description: '家族指示：輪切り4等分をさらに半分（半月）に切って提供。皮は必ず剥く。',
    taskType: 'serve_reminder' as TaskType,
    relatedItemId: 'demo-item-002',
    dueDate: getDateString(-2),
    dueTime: '12:00',
    status: 'completed' as TaskStatus,
    priority: 'high' as TaskPriority,
    assignee: '田中花子',
    completedBy: '田中花子',
    completedAt: getDateTimeString(-2, 12, 30),
    notificationSent: true,
    isAutoGenerated: true,
    createdBy: 'system',
    createdAt: getDateTimeString(-3, 8),
    updatedAt: getDateTimeString(-2, 12, 30),
  },
  {
    id: 'task-008',
    residentId: 'resident-001',
    title: 'カステラの初回提供',
    description: '新しく届いた品物。1切れずつ提供開始。',
    taskType: 'serve_reminder' as TaskType,
    relatedItemId: 'demo-item-007',
    dueDate: getDateString(-1),
    dueTime: '15:00',
    status: 'completed' as TaskStatus,
    priority: 'low' as TaskPriority,
    assignee: '佐藤一郎',
    completedBy: '佐藤一郎',
    completedAt: getDateTimeString(-1, 15, 15),
    notificationSent: true,
    isAutoGenerated: true,
    createdBy: 'system',
    createdAt: getDateTimeString(-2, 8),
    updatedAt: getDateTimeString(-1, 15, 15),
  },

  // ===== カスタムタスク =====
  {
    id: 'task-009',
    residentId: 'resident-001',
    title: '黒豆の提供方法を家族に相談',
    description: '摂食率が40%と低下傾向。煮汁の量や味付けの好みを確認。',
    taskType: 'custom' as TaskType,
    relatedItemId: 'demo-item-011',
    dueDate: getDateString(2),
    status: 'pending' as TaskStatus,
    priority: 'low' as TaskPriority,
    notificationSent: false,
    isAutoGenerated: false,
    createdBy: 'staff-001',
    createdAt: getDateTimeString(-1, 14),
    updatedAt: getDateTimeString(-1, 14),
  },
];

// ===== ヘルパー関数 =====

/**
 * 入居者IDでタスクをフィルタ
 */
export function getDemoTasksForResident(residentId: string): Task[] {
  return DEMO_TASKS.filter(task => task.residentId === residentId);
}

/**
 * ステータスでタスクをフィルタ
 */
export function getDemoTasksByStatus(status: TaskStatus | TaskStatus[]): Task[] {
  const statuses = Array.isArray(status) ? status : [status];
  return DEMO_TASKS.filter(task => statuses.includes(task.status));
}

/**
 * 今日の期限タスクを取得
 */
export function getTodayDemoTasks(): Task[] {
  const today = getDateString(0);
  return DEMO_TASKS.filter(
    task => task.dueDate === today && task.status !== 'completed' && task.status !== 'cancelled'
  );
}

/**
 * 優先度でソート（urgent > high > medium > low）
 */
export function sortDemoTasksByPriority(tasks: Task[]): Task[] {
  const priorityOrder: Record<TaskPriority, number> = {
    urgent: 0,
    high: 1,
    medium: 2,
    low: 3,
  };

  return [...tasks].sort((a, b) => {
    const aPriority = priorityOrder[a.priority || 'medium'];
    const bPriority = priorityOrder[b.priority || 'medium'];
    return aPriority - bPriority;
  });
}

/**
 * 期日でソート（近い順）
 */
export function sortDemoTasksByDueDate(tasks: Task[]): Task[] {
  return [...tasks].sort((a, b) => {
    const aDate = new Date(a.dueDate);
    const bDate = new Date(b.dueDate);
    return aDate.getTime() - bDate.getTime();
  });
}

/**
 * 未完了のタスク数を取得
 */
export function getDemoPendingTaskCount(): number {
  return DEMO_TASKS.filter(
    task => task.status === 'pending' || task.status === 'in_progress'
  ).length;
}
