/**
 * タスク管理 型定義
 * @see docs/TASK_MANAGEMENT_SPEC.md
 */

// === 列挙型 ===

// タスク種別
export type TaskType =
  | 'expiration_warning'  // 賞味期限警告
  | 'serve_reminder'      // 提供リマインダー
  | 'restock_alert'       // 在庫切れアラート
  | 'care_instruction'    // ケア指示確認
  | 'custom';             // カスタムタスク

export const TASK_TYPES: { value: TaskType; label: string; icon: string }[] = [
  { value: 'expiration_warning', label: '賞味期限', icon: '⏰' },
  { value: 'serve_reminder', label: '提供予定', icon: '🍽️' },
  { value: 'restock_alert', label: '在庫切れ', icon: '📦' },
  { value: 'care_instruction', label: 'ケア指示', icon: '📋' },
  { value: 'custom', label: 'その他', icon: '📝' },
];

// タスクステータス
export type TaskStatus =
  | 'pending'      // 未着手
  | 'in_progress'  // 対応中
  | 'completed'    // 完了
  | 'cancelled';   // キャンセル

export const TASK_STATUSES: { value: TaskStatus; label: string; color: string; bgColor: string }[] = [
  { value: 'pending', label: '未着手', color: 'text-yellow-700', bgColor: 'bg-yellow-100' },
  { value: 'in_progress', label: '対応中', color: 'text-blue-700', bgColor: 'bg-blue-100' },
  { value: 'completed', label: '完了', color: 'text-green-700', bgColor: 'bg-green-100' },
  { value: 'cancelled', label: 'キャンセル', color: 'text-gray-700', bgColor: 'bg-gray-100' },
];

// 優先度
export type TaskPriority =
  | 'low'     // 低
  | 'medium'  // 中
  | 'high'    // 高
  | 'urgent'; // 緊急

export const TASK_PRIORITIES: { value: TaskPriority; label: string; color: string; bgColor: string; order: number }[] = [
  { value: 'urgent', label: '緊急', color: 'text-red-700', bgColor: 'bg-red-100', order: 0 },
  { value: 'high', label: '高', color: 'text-orange-700', bgColor: 'bg-orange-100', order: 1 },
  { value: 'medium', label: '中', color: 'text-yellow-700', bgColor: 'bg-yellow-100', order: 2 },
  { value: 'low', label: '低', color: 'text-gray-700', bgColor: 'bg-gray-100', order: 3 },
];

// === インターフェース ===

// タスク（Firestore: tasks/{taskId}）
export interface Task {
  // 識別情報
  id: string;
  residentId: string;

  // タスク内容
  title: string;
  description?: string;
  taskType: TaskType;

  // 関連データ
  relatedItemId?: string;        // 関連する品物ID（care_items）
  relatedInstructionId?: string; // 関連するケア指示ID（care_instructions）

  // スケジュール
  dueDate: string;               // YYYY-MM-DD
  dueTime?: string;              // HH:mm

  // ステータス・優先度
  status: TaskStatus;
  priority: TaskPriority;

  // 担当・実行
  assignee?: string;             // 担当者（スタッフ名）
  completedBy?: string;          // 完了者（スタッフ名）
  completionNote?: string;       // 完了時のメモ

  // 通知
  notificationSent: boolean;

  // 生成情報
  createdBy?: string;            // 'system' or スタッフ名
  isAutoGenerated: boolean;

  // メタ情報
  createdAt: string;             // ISO8601
  updatedAt: string;             // ISO8601
  completedAt?: string;          // ISO8601
}

// === APIリクエスト/レスポンス型 ===

// タスク作成リクエスト
export interface CreateTaskInput {
  residentId: string;
  title: string;
  description?: string;
  taskType?: TaskType;           // デフォルト: 'custom'
  dueDate: string;
  dueTime?: string;
  priority: TaskPriority;
  assignee?: string;
  relatedItemId?: string;
  relatedInstructionId?: string;
}

// タスク更新リクエスト
export interface UpdateTaskInput {
  status?: TaskStatus;
  assignee?: string;
  completionNote?: string;
  completedBy?: string;
}

// タスク一覧取得パラメータ
export interface GetTasksParams {
  residentId?: string;
  status?: TaskStatus | TaskStatus[];
  taskType?: TaskType;
  priority?: TaskPriority;
  dueDate?: string;
  dueDateStart?: string;
  dueDateEnd?: string;
  limit?: number;
  offset?: number;
  sortBy?: 'dueDate' | 'priority' | 'createdAt';
  sortOrder?: 'asc' | 'desc';
}

// タスク一覧レスポンス
export interface GetTasksResponse {
  tasks: Task[];
  total: number;
  counts: TaskCounts;
}

// タスク件数
export interface TaskCounts {
  pending: number;
  inProgress: number;
  completed: number;
  overdue: number;
}

// タスク作成レスポンス
export interface CreateTaskResponse {
  taskId: string;
  createdAt: string;
}

// タスク更新レスポンス
export interface UpdateTaskResponse {
  taskId: string;
  status: TaskStatus;
  updatedAt: string;
}

// === ユーティリティ関数 ===

/**
 * タスク種別のラベルを取得
 */
export function getTaskTypeLabel(taskType: TaskType): string {
  return TASK_TYPES.find(t => t.value === taskType)?.label ?? taskType;
}

/**
 * タスク種別のアイコンを取得
 */
export function getTaskTypeIcon(taskType: TaskType): string {
  return TASK_TYPES.find(t => t.value === taskType)?.icon ?? '📝';
}

/**
 * ステータスのラベルを取得
 */
export function getTaskStatusLabel(status: TaskStatus): string {
  return TASK_STATUSES.find(s => s.value === status)?.label ?? status;
}

/**
 * ステータスの色クラスを取得
 */
export function getTaskStatusColorClass(status: TaskStatus): { color: string; bgColor: string } {
  const statusConfig = TASK_STATUSES.find(s => s.value === status);
  return {
    color: statusConfig?.color ?? 'text-gray-700',
    bgColor: statusConfig?.bgColor ?? 'bg-gray-100',
  };
}

/**
 * 優先度のラベルを取得
 */
export function getTaskPriorityLabel(priority: TaskPriority): string {
  return TASK_PRIORITIES.find(p => p.value === priority)?.label ?? priority;
}

/**
 * 優先度の色クラスを取得
 */
export function getTaskPriorityColorClass(priority: TaskPriority): { color: string; bgColor: string } {
  const priorityConfig = TASK_PRIORITIES.find(p => p.value === priority);
  return {
    color: priorityConfig?.color ?? 'text-gray-700',
    bgColor: priorityConfig?.bgColor ?? 'bg-gray-100',
  };
}

/**
 * 優先度でソートするための順序を取得
 */
export function getTaskPriorityOrder(priority: TaskPriority): number {
  return TASK_PRIORITIES.find(p => p.value === priority)?.order ?? 99;
}

/**
 * タスクが期限切れかどうかを判定
 */
export function isTaskOverdue(task: Task): boolean {
  if (task.status === 'completed' || task.status === 'cancelled') {
    return false;
  }
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const dueDate = new Date(task.dueDate);
  dueDate.setHours(0, 0, 0, 0);
  return dueDate < today;
}

/**
 * 期限までの日数を計算
 */
export function getDaysUntilDue(dueDate: string): number {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const due = new Date(dueDate);
  due.setHours(0, 0, 0, 0);
  const diffTime = due.getTime() - today.getTime();
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
}

/**
 * 期限の表示テキストを取得
 */
export function getDueDateDisplayText(dueDate: string): string {
  const days = getDaysUntilDue(dueDate);
  if (days < 0) {
    return `${Math.abs(days)}日前`;
  } else if (days === 0) {
    return '今日';
  } else if (days === 1) {
    return '明日';
  } else if (days <= 7) {
    return `${days}日後`;
  } else {
    return formatTaskDate(dueDate);
  }
}

/**
 * 日付をフォーマット（MM/DD形式）
 */
export function formatTaskDate(dateStr: string): string {
  if (!dateStr) return '';
  const date = new Date(dateStr);
  const m = date.getMonth() + 1;
  const d = date.getDate();
  return `${m}/${d}`;
}

/**
 * 日時をフォーマット（MM/DD HH:mm形式）
 */
export function formatTaskDateTime(dateStr: string, timeStr?: string): string {
  const date = formatTaskDate(dateStr);
  if (timeStr) {
    return `${date} ${timeStr}`;
  }
  return date;
}
